"""empty message

Revision ID: 122683ae59d2
Revises: 10dd18eca4e6
Create Date: 2024-11-26 00:51:41.211512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122683ae59d2'
down_revision = '10dd18eca4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
